# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  contentDir: content/en
  languageCode: en-us
  languageName: English
  weight: 1
  baseURL: "https://robinchen95.com/en/"

zh:
  contentDir: content/zh
  languageCode: zh
  languageName: 中文
  weight: 2
  baseURL: "https://robinchen95.com/zh/"

ja:
  contentDir: content/ja
  languageCode: ja
  languageName: 日本語
  weight: 3
  baseURL: "https://robinchen95.com/ja/"